pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                //Original line from the lab
		//sh 'uname -a'
		echo "this is the main branch."
            }
        }
    }
}
